# Generated by Django 5.1 on 2024-08-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('foto_perfil', models.ImageField(upload_to='fotos_perfil/')),
                ('biografia', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('numero_telefonico', models.CharField(blank=True, max_length=15, null=True)),
                ('redes_sociales', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
